import avatar from './img/userAva.png';
export let initialState = {
    users: [
        { 
            id: 1,
            preview: avatar,
            firstName: 'Евгений',
            lastName: 'Скобелев',
            dateOfBirth: '12.03.1998',
            age: '22',
            position: 'Разработчик',
            remoteWorking: true,
            adress: 'СПБ, ул. Маршала Говорова, дом 3, кв. 156',
        },
        { 
            id: 2,
            preview: avatar,
            firstName: 'Максим',
            lastName: 'Евстигнеев',
            dateOfBirth: '01.10.1999',
            age: '21',
            position: 'Разработчик',
            remoteWorking: true,
            adress: 'СПБ, пр. Стачек , дом 101, кв. 8',
        },
        { 
            id: 3,
            preview: avatar,
            firstName: 'Андрей',
            lastName: 'Петров',
            dateOfBirth: '18.02.1999',
            age: '21',
            position: 'Тестировщик',
            remoteWorking: false,
            adress: 'СПБ, ул. Репищева, дом 15 строение 2, кв. 12',
        },
        { 
            id: 4,
            preview: avatar,
            firstName: 'Валерий',
            lastName: 'Сетунь',
            dateOfBirth: '23.04.1997',
            age: '23',
            position: 'Тестировщик',
            remoteWorking: false,
            adress: 'СПБ, пр-д Соломахинский, дом 4, кв. 17',
        },
        { 
            id: 5,
            preview: avatar,
            firstName: 'Максим',
            lastName: 'Кошкин',
            dateOfBirth: '28.06.1995',
            age: '24',
            position: 'Дизайнер',
            remoteWorking: true,
            adress: 'СПБ, ул. Восстания, дом 20, кв. 5',
        },
        { 
            id: 6,
            preview: avatar,
            firstName: 'Алексей',
            lastName: 'Ковалёв',
            dateOfBirth: '17.07.1999',
            age: '21',
            position: 'HR',
            remoteWorking: true,
            adress: 'СПБ, ул. Парашютная, дом 46 строение 3, кв. 367',
        },
        { 
            id: 7,
            preview: avatar,
            firstName: 'Юрий',
            lastName: 'Патрушев',
            dateOfBirth: '11.10.1995',
            age: '25',
            position: 'Верстальщик',
            remoteWorking: true,
            adress: 'СПБ, ул. Кропоткина, дом 17, кв. 2',
        },
        { 
            id: 8,
            preview: avatar,
            firstName: 'Алексей',
            lastName: 'Ильинский',
            dateOfBirth: '30.06.2000',
            age: '19',
            position: 'Стажёр',
            remoteWorking: false,
            adress: 'СПБ, ул. Красного Курсанта, дом 12, кв. 27',
        },
    ],
    choosenUser: 0,
  };